EspritClub/src/Entity/Club.php
<?php

namespace App\Entity;

use App\Repository\ClubRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ClubRepository::class)
 */
class Club
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $ref;

    /**
     * @ORM\Column(type="date")
     */
    private $creation_date;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getRef(): ?string
    {
        return $this->ref;
    }

    public function setRef(string $ref): self
    {
        $this->ref = $ref;

        return $this;
    }

    public function getCreationDate(): ?\DateTimeInterface
    {
        return $this->creation_date;
    }

    public function setCreationDate(\DateTimeInterface $creation_date): self
    {
        $this->creation_date = $creation_date;

        return $this;
    }
}

EspritClub/src/Controller/ClubController.php
<?php
namespace App\Controller;
use App\Entity\Club;
use App\Form\ClubformType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
class ClubController extends AbstractController
{
    /**
     * @Route("/club", name="club")
     */
    public function index()
    {
        /*return $this->render('club/index.html.twig', [
            'controller_name' => 'ClubController',
        ]);*/
        $em=$this->getDoctrine()->getManager();
        $club= new club();
        $form = $this->createForm(ClubformType::class,$club);
        if($request->isMethod('POST') && $form->handleRequest($request)->isValid())
        {
            $em->persist($club);
            $em->flush();
        }
        return $this-> render('club/index.html.twig',[
            'form' => $form ->createView(),
        ]);
    }
    /**
     * @param $nom
     * @Route("/Affiche/{nom}")
     */
   /* function getName($nom)
    {
        return $this->render('club/AfficheNom.html.twig',
            ['n' =>$nom]);
    }*/

    /**
     * @return \Symfony\Component\HttpFoundation\Response
     * @Route("/Liste")
     */
  /*  function Liste(){
       $formations =[
            array('ref'=>'form1', 'Titre'=>'Formation Symfony 3.4','Description'=>'formation
pratique','date_debut'=>'12/06/2020', 'date_fin'=>'19/06/2020',
                'nb_participants'=>'19'),
            array('ref'=>'form2', 'Titre'=>'Formation Angular7','Description'=>'formation
theorique','date_debut'=>'01/11/2020', 'date_fin'=>'05/11/2020',
                'nb_participants'=>'0'),
            array ('ref'=>'form3', 'Titre'=>'Formation NodeJs','Description'=>'formation
pratique','date_debut'=>'12/12/2020', 'date_fin'=>'15/12/2020',
                'nb_participants'=>'10')
        ];
           return  $this ->render("club/Liste.html.twig",
               ['formation'=>$formations]);
    }*/

    /**
     * @Route("/d/{id}", name="detail")
     */
   /* function Detail($id){
        return $this->render("club/Detail.html.twig",
            ['ref'=>$id]);

    }*/
    /**
     * @return \Symfony\Component\HttpFoundation\Response
     * @Route("/listclub", name="listeclub")
     */
    public function ListClub()
    {
        $clubs = $this->getDoctrine()->getRepository(club::class)->findAll();
        return $this->render("club/Listclub.html.twig", array("clubs" => $clubs));
    }
    /**
     * @Route("/removeclub/{id}", name="removeclub")
     */
    public function remove($id)
    {
        $clubs = $this->getDoctrine()->getRepository(club::class)->find($id);
        $em = $this->getDoctrine()->getManager();

        $em->remove($clubs);
        $em->flush();
        return $this->redirectToRoute('listeclub');
    }
    /**
     * @Route("/addclub", name="addclub")
     */
    public function add(Request $request)
    {
        $club = new Club();
        $form = $this->createForm(ClubformType::class, $club);
        $form->handleRequest($request);
        if ($form->isSubmitted()) {
            $em = $this->getDoctrine()->getManager();
            $em->persist($club); // ajout
            $em->flush(); //flush
            return $this->redirectToRoute("listeclub"); //redirection
            }
        return $this->render("club/add.html.twig", array('formulaire' => $form->createView()));
    }

    /**
     * @Route("/updateclub/{id}", name="updateclub")
     */
    public function update(Request $request, $id)
    {
        $club = $this->getDoctrine()->getRepository(club::class)->find($id);
        $form = $this->createForm(ClubformType::class, $club);
        $form->handleRequest($request);
        if ($form->isSubmitted()) {
            $em = $this->getDoctrine()->getManager();
            $em->flush();
            return $this->redirectToRoute("listeclub"); //redirection}
        }
        return $this->render("club/update.html.twig", array('formulaire' => $form->createView()));
    }
}

EspritClub/templates/club/AfficheNom.html.twig
Bonjour {{ n }}

EspritClub/templates/club/Detail.html.twig
La reference de la formation est :{{  ref  }}

EspritClub/templates/club/Listclub.html.twig
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
<div class="container pt-2 text-center">
    <h1>Affiche clubs</h1>
    <center>
<table border="1">
    <thead>
    <tr>
        <th>Id</th>
        <th>Ref</th>
        <th>Creation date</th>
    </tr>
    </thead>
    <tbody>
    {% for i in clubs %}
        <tr>
            <td>{{ i.id }} </td>
            <td>{{i.ref}}</td>
            <td>{{i.creationDate |date("m/d/Y")}}</td>
            <td> <a href="{{ path('removeclub',{'id':i.id}) }}">Remove</a></td>
            <td> <a href="{{ path('updateclub',{'id':i.id}) }}">Update</a></td>
        </tr>
    {%  endfor %}
    </tbody>
</table>
    </center>
<a href ="{{ path("addclub") }}">Add</a>
</div>
</body>
</html>

EspritClub/templates/club/Liste.html.twig
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
<h1>Le nombre de formation est {{ formation | length }}</h1>
{% set nbMax=0 %}
{% for form in formation %}
    {% set nbMax=max(form.nb_participants,nbMax) %}
{% endfor %}
<table border="1">
    <tr>
        <th>Reference</th>
        <th>Titre</th>
        <th>Description</th>
        <th>Date Debut</th>
        <th>Date fin</th>
        <th>Nb Participants</th>
    </tr>
    {% for f in formation %}
    <tr>
     {#  {% if 'theorique' in f.Description %} #}
      {#  {% if f.nb_participants == nbMax %} #}
        <td>{{ f.ref }}</td>
        <td>{{  f.Titre |upper}}</td>
        <td>{{  f.Description}}</td>
        <td>{{ f.date_debut }}</td>
        <td>{{ f.date_fin }}</td>
        <td>{{ f.nb_participants }}</td>

        {#  {% else  %}   #}
        {#<strong>Tableau Vide</strong>    #}
        {#  {% endif %}#}
                <td>
                    {% if f.nb_participants == 0 %}
                        <form action="{{ path('detail',{'id':f.ref}) }}">
                            <button>Participer</button>
                        </form>

                    {% endif %}
                </td>
                </tr>
    {%  endfor %}
</table>
{% set nbTot=0 %}
{% for f in formation %}
    {%  set nbTot=nbTot+f.nb_participants %}
{% endfor %}
<p>le nbr total des participans est: {{  nbTot }}</p>
</body>
</html>

EspritClub/templates/club/add.html.twig
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <title>Document</title>
</head>
<body>
<div class="container pt-3 text-center">
    <h1>add Club</h1>
    {{ form(formulaire) }}
</div>
</body>
</html>

EspritClub/templates/club/index.html.twig
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
<h1>Clubs Esprit</h1>
<p>Bonjour à tous</p>
<img src="{{ asset('images/esprit.jpg') }}" alt="">
</body>
</html>

EspritClub/templates/club/update.html.twig
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <title>Document</title>
</head>
<body>
<div class="container pt-3 text-center">
    <h1>edit club</h1>
    {{ form(formulaire) }}
</div>
</body>
</html>